name: Create PR

on: pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 'latest'
            - name: install
              run: yarn
            - name: install p5
              run: yarn add p5
            - name: install @types/p5
              run: yarn add p5
            - name: lint
              run: yarn lint
            - name: build
              run: yarn build
            - name: test
              run: yarn test
            - name: build example
              run: yarn build:example
            - name: clean-up
              run: rm -rf temp-build
